version: '3'

services:
  maildev:
    extends:
      file: docker-compose.all.yml
      service: maildev
  qdrant:
    extends:
      file: docker-compose.all.yml
      service: qdrant
  pgdb:
    extends:
      file: docker-compose.all.yml
      service: pgdb
  pgadmin:
    extends:
      file: docker-compose.all.yml
      service: pgadmin
  redis:
    image: 'redis:6'
    user: '999:999'
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '127.0.0.1:${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    depends_on:
      - redis
    ports:
      - '127.0.0.1:${REDIS_UI_PORT}:7843'
    volumes:
      - p3x-redis-ui-settings:/settings
  minio:
    extends:
      file: docker-compose.all.yml
      service: minio
  init_bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 root password;
      /usr/bin/mc mb minio/chaindesk;
      /usr/bin/mc anonymous set public minio/chaindesk;
      exit 0;
      "

volumes:
  pgdb-data:
  pgadmin-data:
  redis-data:
  redis-conf:
  p3x-redis-ui-settings:
  minio:
